export const root: string;
export const heroWrapper: string;
export const socialHero: string;
export const builtHero: string;
export const marriottHero: string;
export const fannieHero: string;
export const bullets: string;
export const outroTitle: string;
export const result: string;
